version: "3.8"
services:
  postgresql:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: metricdb  

  zookeper:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181   

  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "metrics:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181  
