postgresql:
  host: 0.0.0.0
  port: 5432
  user: postgres
  password: 1
  dbname: metricdb

#non node specialization specific settings
kafka:
  bootstrap_servers: ["localhost:9092"]

#specific settings for producers
kafka_prod:

#specific settings for consumers
kafka_cons:
  auto_offset_reset: latest

application:
  chunk_size: 5 #defines chunk sizes pushed to DB simultaneously
  update_interval: 5 #defines intervals between service availability polls

#services under monitoring list host -> page(one or more) -> regexp(for page)
monitoring:
  ya.ru:
    "":
      regexp:
  exante.eu:
    ru:
      regexp:
    en:
      regexp:
  habr.com:
    "ru/all":
      regexp:

test:
  monitoring:
    "localhost:18803":
      start:
        regexp: "start"
      end:
        regexp: "word"
