postgresql:
  host:
  port:
  user:
  password:
  dbname:

kafka:

application:
  ask_interval: 10
  dump_interval: 20

monitoring:
  ya.ru:
    "":
      regexp:
  exante.eu:
    ru:
      regexp:
  habr.com:
    "ru/all":
      regexp: